In [2]:
import torch
import torch.nn as nn
import numpy as np
import scanpy as sc

ModuleNotFoundError: No module named 'notebooks.transformer'

In [ ]:
adata = sc.read_h5ad('/orcd/archive/abugoot/001/Projects/dlesman/datasets/satija_IFNB_HVG_and_perturbed_genes_raw.h5ad')

In [ ]:
observation_groups = adata.obs.groupby(['gene', 'cell_type','Batch_info'])

adata.obs['group_id'] = observation_groups.ngroup()

adata.obs[adata.obs['group_id'] == 1]

,orig.ident,nCount_RNA,nFeature_RNA,sample,bc1_well,bc2_well,bc3_well,percent.mito,cell_type,pathway,RNA_snn_res.0.9,seurat_clusters,sample_ID,Batch_info,guide,gene,mixscale_score,group_id
07_02_54_1_1_1_1_1_1_1_1_2,7,7170,3435,A549_IFNB,A7,A2,E6,3.682008,A549,IFNB,NaN,NaN,sample_1,Rep2,ADARg3,ADAR,1.658515,1
07_68_35_1_1_1_1_1_1_1_1_2,7,6640,3089,A549_IFNB,A7,F8,C11,6.024096,A549,IFNB,NaN,NaN,sample_1,Rep2,ADARg3,ADAR,0.814965,1
06_32_04_1_1_1_1_1_1_1_1_2,6,5790,2836,A549_IFNB,A6,C8,A4,1.174439,A549,IFNB,NaN,NaN,sample_1,Rep2,ADARg1,ADAR,3.083483,1
06_70_83_1_1_1_1_1_1_1_1_2,6,5396,2743,A549_IFNB,A6,F10,G11,0.648629,A549,IFNB,NaN,NaN,sample_1,Rep2,ADARg2,ADAR,0.269885,1
07_59_07_1_1_1_1_1_1_1_1_2,7,4849,2465,A549_IFNB,A7,E11,A7,2.227263,A549,IFNB,NaN,NaN,sample_1,Rep2,ADARg3,ADAR,0.055679,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
08_47_49_2_2,8,3798,2176,A549_IFNB,A8,D11,E1,2.106372,A549,IFNB,NaN,NaN,sample_16,Rep2,ADARg1,ADAR,2.554883,1
05_66_58_2_2,5,3643,2134,A549_IFNB,A5,F6,E10,1.152896,A549,IFNB,NaN,NaN,sample_16,Rep2,ADARg1,ADAR,-0.169589,1
05_25_13_2_2,5,3068,1773,A549_IFNB,A5,C1,B1,1.466754,A549,IFNB,NaN,NaN,sample_16,Rep2,ADARg2,ADAR,0.299870,1
05_25_03_2_2,5,3067,1728,A549_IFNB,A5,C1,A3,1.988914,A549,IFNB,NaN,NaN,sample_16,Rep2,ADARg2,ADAR,5.612801,1
05_04_79_2_2,5,2706,1678,A549_IFNB,A5,A4,G7,0.886918,A549,IFNB,NaN,NaN,sample_16,Rep2,ADARg1,ADAR,0.587944,1

In [4]:

adata[observation_groups.indices[('ADAR', 'A549', 'Rep1')]].obs['group'] = 1

adata.obs

/tmp/ipykernel_1799883/2445355060.py:1: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  adata[observation_groups.indices[('ADAR', 'A549', 'Rep1')]].obs['group'] = 1

,orig.ident,nCount_RNA,nFeature_RNA,sample,bc1_well,bc2_well,bc3_well,percent.mito,cell_type,pathway,RNA_snn_res.0.9,seurat_clusters,sample_ID,Batch_info,guide,gene,mixscale_score,group_id
07_48_88_1_1_1_1_1_1_1_1_1,7,9816,4122,A549_IFNB,A7,D12,H4,1.161369,A549,IFNB,15.0,15.0,sample_1,Rep1,TRAFD1g3,TRAFD1,-0.290358,624
06_04_63_1_1_1_1_1_1_1_1_1,6,9359,4112,A549_IFNB,A6,A4,F3,3.835880,A549,IFNB,15.0,15.0,sample_1,Rep1,HES4g3,HES4,0.121449,192
06_28_67_1_1_1_1_1_1_1_1_1,6,8999,3854,A549_IFNB,A6,C4,F7,9.189910,A549,IFNB,15.0,15.0,sample_1,Rep1,NTg8,NT,0.000000,432
06_27_93_1_1_1_1_1_1_1_1_1,6,8384,3600,A549_IFNB,A6,C3,H9,3.268130,A549,IFNB,15.0,15.0,sample_1,Rep1,STAT5Ag1,STAT5A,0.377627,600
06_81_38_1_1_1_1_1_1_1_1_1,6,7925,3580,A549_IFNB,A6,G9,D2,3.798107,A549,IFNB,15.0,15.0,sample_1,Rep1,STAT4g2,STAT4,1.000000,588
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
09_10_48_2_2,9,2362,1491,MCF7_IFNB,A9,A10,D12,1.820491,MCF7,IFNB,NaN,NaN,sample_16,Rep2,NFE2L3g3,NFE2L3,-0.009685,419
10_73_27_2_2,10,2143,1483,MCF7_IFNB,A10,G1,C3,0.326645,MCF7,IFNB,NaN,NaN,sample_16,Rep2,IRF3g2,IRF3,-0.402627,299
10_24_48_2_2,10,1921,1322,MCF7_IFNB,A10,B12,D12,6.507028,MCF7,IFNB,NaN,NaN,sample_16,Rep2,STAT6g2,STAT6,-0.356580,623
10_12_27_2_2,10,1676,1169,MCF7_IFNB,A10,A12,C3,2.923628,MCF7,IFNB,NaN,NaN,sample_16,Rep2,HERC5g3,HERC5,-0.045158,179
10_83_89_2_2,10,1538,1168,MCF7_IFNB,A10,G11,H5,1.820546,MCF7,IFNB,NaN,NaN,sample_16,Rep2,MAPK8g2,MAPK8,4.383990,371

In [5]:
# Assign to each observation it's group

for i, key in enumerate(list(observation_groups.indices)[:2]):
    print(key)
    adata[observation_groups.indices[key]].obs['group'] = i 

adata.obs

('ADAR', 'A549', 'Rep1')

/tmp/ipykernel_1799883/336399944.py:5: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  adata[observation_groups.indices[key]].obs['group'] = i

('ADAR', 'A549', 'Rep2')

/tmp/ipykernel_1799883/336399944.py:5: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  adata[observation_groups.indices[key]].obs['group'] = i

,orig.ident,nCount_RNA,nFeature_RNA,sample,bc1_well,bc2_well,bc3_well,percent.mito,cell_type,pathway,RNA_snn_res.0.9,seurat_clusters,sample_ID,Batch_info,guide,gene,mixscale_score,group_id
07_48_88_1_1_1_1_1_1_1_1_1,7,9816,4122,A549_IFNB,A7,D12,H4,1.161369,A549,IFNB,15.0,15.0,sample_1,Rep1,TRAFD1g3,TRAFD1,-0.290358,624
06_04_63_1_1_1_1_1_1_1_1_1,6,9359,4112,A549_IFNB,A6,A4,F3,3.835880,A549,IFNB,15.0,15.0,sample_1,Rep1,HES4g3,HES4,0.121449,192
06_28_67_1_1_1_1_1_1_1_1_1,6,8999,3854,A549_IFNB,A6,C4,F7,9.189910,A549,IFNB,15.0,15.0,sample_1,Rep1,NTg8,NT,0.000000,432
06_27_93_1_1_1_1_1_1_1_1_1,6,8384,3600,A549_IFNB,A6,C3,H9,3.268130,A549,IFNB,15.0,15.0,sample_1,Rep1,STAT5Ag1,STAT5A,0.377627,600
06_81_38_1_1_1_1_1_1_1_1_1,6,7925,3580,A549_IFNB,A6,G9,D2,3.798107,A549,IFNB,15.0,15.0,sample_1,Rep1,STAT4g2,STAT4,1.000000,588
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
09_10_48_2_2,9,2362,1491,MCF7_IFNB,A9,A10,D12,1.820491,MCF7,IFNB,NaN,NaN,sample_16,Rep2,NFE2L3g3,NFE2L3,-0.009685,419
10_73_27_2_2,10,2143,1483,MCF7_IFNB,A10,G1,C3,0.326645,MCF7,IFNB,NaN,NaN,sample_16,Rep2,IRF3g2,IRF3,-0.402627,299
10_24_48_2_2,10,1921,1322,MCF7_IFNB,A10,B12,D12,6.507028,MCF7,IFNB,NaN,NaN,sample_16,Rep2,STAT6g2,STAT6,-0.356580,623
10_12_27_2_2,10,1676,1169,MCF7_IFNB,A10,A12,C3,2.923628,MCF7,IFNB,NaN,NaN,sample_16,Rep2,HERC5g3,HERC5,-0.045158,179
10_83_89_2_2,10,1538,1168,MCF7_IFNB,A10,G11,H5,1.820546,MCF7,IFNB,NaN,NaN,sample_16,Rep2,MAPK8g2,MAPK8,4.383990,371