In [1]:
import scanpy as sc

In [2]:
adata = sc.read('/orcd/data/omarabu/001/Omnicell_datasets/satija_IFNG_raw/Seurat_IFNG.h5ad')

In [3]:
adata.obs

,orig.ident,nCount_RNA,nFeature_RNA,sample,cell_type,pathway,percent.mito,sample_ID,Batch_info,bc1_well,bc2_well,bc3_well,guide,gene,mixscale_score
05_54_42_1_1_1_1_1_1_1_1_1,5,15381,5362,A549_IFNG,A549,IFNG,5.961901,sample_1,Rep1,NaN,NaN,NaN,ATF3g2,ATF3,1.176385
08_58_81_1_1_1_1_1_1_1_1_1,8,13534,4995,A549_IFNG,A549,IFNG,1.780700,sample_1,Rep1,NaN,NaN,NaN,STAT2g1,STAT2,-0.787551
06_01_92_1_1_1_1_1_1_1_1_1,6,11520,4454,A549_IFNG,A549,IFNG,9.644097,sample_1,Rep1,NaN,NaN,NaN,CUL1g1,CUL1,4.208174
05_33_45_1_1_1_1_1_1_1_1_1,5,11174,4575,A549_IFNG,A549,IFNG,4.966887,sample_1,Rep1,NaN,NaN,NaN,IRF2g2,IRF2,-0.345167
06_35_73_1_1_1_1_1_1_1_1_1,6,10807,3961,A549_IFNG,A549,IFNG,13.528269,sample_1,Rep1,NaN,NaN,NaN,MYCg2,MYC,-0.182128
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10_82_89_2_2,10,1102,872,MCF7_IFNG,MCF7,IFNG,1.451906,sample_16,Rep2,A10,G10,H5,JAK2g3,JAK2,1.877012
10_30_41_2_2,10,1083,824,MCF7_IFNG,MCF7,IFNG,3.785780,sample_16,Rep2,A10,C6,D5,STAT1g2,STAT1,3.666724
10_09_53_2_2,10,1071,845,MCF7_IFNG,MCF7,IFNG,1.213819,sample_16,Rep2,A10,A9,E5,STAT3g2,STAT3,1.025512
09_96_96_2_2,9,941,781,MCF7_IFNG,MCF7,IFNG,1.062699,sample_16,Rep2,A9,H12,H12,ATF5g2,ATF5,5.242902
12_77_43_2_2,12,938,655,MCF7_IFNG,MCF7,IFNG,3.837953,sample_16,Rep2,A12,G5,D7,STAT1g1,STAT1,1.493807

In [11]:
adata.var['gene'] = adata.var['c..TSPAN6....TNMD....DPM1....SCYL3....C1orf112....FGR....CFH...']

In [12]:
adata.var_names = adata.var['gene']

In [13]:
adata.var

,c..TSPAN6....TNMD....DPM1....SCYL3....C1orf112....FGR....CFH...,gene
gene,,
TSPAN6,TSPAN6,TSPAN6
TNMD,TNMD,TNMD
DPM1,DPM1,DPM1
SCYL3,SCYL3,SCYL3
C1orf112,C1orf112,C1orf112
...,...,...
AC068620.2,AC068620.2,AC068620.2
AC006023.1,AC006023.1,AC006023.1
AL356121.2,AL356121.2,AL356121.2
TAF9BP2,TAF9BP2,TAF9BP2
AC016065.2,AC016065.2,AC016065.2

In [14]:
adata.write('/orcd/data/omarabu/001/Omnicell_datasets/satija_IFNG_raw/Seurat_IFNG.h5ad')

In [17]:
adata.X

<245240x33525 sparse matrix of type '<class 'numpy.float64'>'
	with 667070362 stored elements in Compressed Sparse Column format>